title: commonplace.7robots.org
description: jefferson burson's online commonplace books. a collection of notes, articles, book quotes, and random information.
theme: just-the-docs

url: https://commonplace.7robots.org

logo: "/assets/Moon.jpeg"
color_scheme: dark
nav_external_links_new_tab: true

callouts:
  selene:
    title: selene
    color: grey-lt
  anthologia:
    title: anthologia
    color: red
  hypomnemata:
    title: hypomnemata
    color: green
  polis:
    title: polis
    color: blue
  agora:
    title: agora
    color: yellow
  melete:
    title: melete
    color: purple   
  techne:
    title: techne
    color: grey-lt
    
#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
